settings:
  static_bias_initialization: false
  initialize_state_from_first_observation: true
  imu_topic: "/imu"
  map_frame_id : "/map"
  base_frame_id: "/imu"
  pose_topic: "/pose"
  state_topic: "/state"
  publish_visualization_markers: false
  visualization_markers_topic: "/markers"
  enable_landmarks: false
  landmarks_topic: "/landmarks"
  enable_kinematics: true
  kinematics_topic: "/kinematics"
  contact_topic: "/contacts"


